version: '3'

networks:
  study-net:
    driver: bridge

services:
  pg:
    image: postgres
    container_name: study-pg
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - ./.pgdata:/var/lib/postgresql/data/pgdata
      - ./pginit/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    networks:
      - study-net

  bh:
    build: bh
    container_name: study-bh
    restart: always
    volumes:
      - ./logs:/logs
    environment:
      - JDBC_URL=jdbc:postgresql://study-pg:5432/dev?ssl=false
      - DB_USERNAME=dev
      - DB_PASSWORD=dev
    networks:
      - study-net

  tg:
    build: tg
    container_name: study-tg
    restart: always
    volumes:
      - ./logs:/logs
    environment:
      - JDBC_URL=jdbc:postgresql://study-pg:5432/dev?ssl=false
      - DB_USERNAME=dev
      - DB_PASSWORD=dev
    env_file:
      - .env
    networks:
      - study-net

  web:
    build: web
    container_name: study-web
    restart: always
    volumes:
      - ./logs:/logs
    ports:
      - "8080:8080"
    environment:
      - BH_ADDRESS=static://study-bh:6565
      - TG_ADDRESS=static://study-tg:6565
    networks:
      - study-net